### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by thinkgenome** [chevrm/impact#1]
Hi Mark,

After installing transPACT in a docker container, while running the example input, I am getting following errors:

(transPACTtest) root@53bfa0f32c93:/transPACT# pwd
/transPACT
(transPACTtest) root@53bfa0f32c93:/transPACT# ls
LICENSE  README.md  aligned.fasta  antismash  conda_packages.txt  data	example  images  in_seq.fasta  mags  transPACT_substrate_from_faa.py
(transPACTtest) root@53bfa0f32c93:/transPACT# python2 transPACT_substrate_from_faa.py example/test.faa

Error Log:
Traceback (most recent call last):
  File "/transPACT/transPACT_substrate_from_faa.py", line 540, in <module>
    alignment_file = align_ks_domains(ra, ks_names, ks_seqs)
  File "/transPACT/transPACT_substrate_from_faa.py", line 53, in align_ks_domains
    out, err, retcode = utils.execute(muscle_cmd.split(" "))
  File "/transPACT/antismash/utils.py", line 480, in execute
    stderr=subprocess.PIPE)
  File "/opt/conda/envs/transPACTtest/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/opt/conda/envs/transPACTtest/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Let me know if I should try some thing differently.

Best,
Shrikant

**Comment by chevrm** [comment]
It appears the dependency `muscle` was not included in the conda package list. This has been updated.

Within your current docker, you can install it with `conda install --channel "bioconda" muscle` or you can start a new conda environment using the recently pushed version of `conda_packages.txt`

**Comment by thinkgenome** [comment]
Thanks
